# rules/prometheus-rules.yml
groups:
  - name: email-api-slos
    rules:
      - alert: HighValidationLatencyP99
        expr: histogram_quantile(0.99, sum by (le) (rate(email_validation_business_validation_duration_seconds_bucket[10m]))) > 5
        for: 10m
        labels: {severity: page}
        annotations:
          summary: "P99 validación > 5s (10m)"
      - alert: HighQueueDepthV2
        expr: max without(instance) (
                max_over_time(email_validation_business_job_queue_depth{instance=~"worker:.*"}[2m])
              ) > 100
        for: 5m
        labels: {severity: warn}
        annotations: {summary: "Profundidad de cola sostenida > 100 (≥5m)"}
